=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornellPablo-eventos-1/xml/EventoCultural.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/EventoCultural"
	xmlns:tns="http://www.example.org/EventoCultural"
	elementFormDefault="qualified">

	<element name="eventoCultural">
		<complexType>
			<sequence>
				<element name="nombre" minOccurs="1" />
				<element name="fechaInicio" minOccurs="1" />
				<element name="fechaFin" minOccurs="1" />
				<element name="resumen" />
				<element name="url" minOccurs="1" />
				<element name="urlWikipedia" minOccurs="0" />
				<element name="localizacion" minOccurs="1" />
				<element name="coordenadaLongitud" type="tns:tipoCoordenada"
					minOccurs="1" />
				<element name="coordenadaLatitud" type="tns:tipoCoordenada"
					minOccurs="1" />
				<element name="actuaciones" type="tns:tipoActuaciones"
					minOccurs="0" />
			</sequence>
			<attribute name="id" use="required" />
		</complexType>
	</element>

	<complexType name="tipoActuaciones">
		<sequence>
			<element name="frecuencia" type="string" />
			<element name="dias" type="string" />
			<element name="intervalo" type="integer" />
		</sequence>
	</complexType>

	<simpleType name="tipoCoordenada">
		<restriction base="double" />
	</simpleType>

</schema>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornell-Pablo-eventos-rest/xmlEventosRepositorio/30466ee4-4806-41bc-822d-60f6c6823924.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="30466ee4-4806-41bc-822d-60f6c6823924" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>Activadas. Club de empleo y emprendimiento</nombre>
    <tipo>CursosTalleres</tipo>
    <fechaInicio>2021-06-02</fechaInicio>
    <fechaFin>2021-06-02</fechaFin>
    <resumen>Estás en búsqueda de empleo? ¿Quieres cambiar de trabajo, formarte o reciclarte? ¿Quieres emprender y no sabes por dónde empezar?  ¡Descubre que no estás sola!  Cada semana nos encontramos en este espacio de sororidad y empoderamiento, para apoyarnos, compartir y acompañarnos en el proceso. ¡No te los pierdas!  Taller presencial. Imprescindible inscripción previa.   Todos los miércoles de 10:30 a 11:30 h.</resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=93d1b6e17ad44710VgnVCM1000001d4a900aRCRD</url>
    <localizacion>Espacio de Igualdad Carme Chacón. Hortaleza</localizacion>
    <coordenadaLongitud>-3.6501714580414126</coordenadaLongitud>
    <coordenadaLatitud>40.46155641637237</coordenadaLatitud>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
    <sitiosInteres>
        <titulo>Estación de Arturo Soria</titulo>
        <resumen>Arturo Soria es una estación de la línea 4 del Metro de Madrid situada bajo el cruce de las calles Arturo Soria, José Silva y Ulises, en el madrileño distrito de Ciudad Lineal.  (...)</resumen>
        <urlWikipedia>https://es.wikipedia.org/wiki/Estaci%C3%B3n_de_Arturo_Soria</urlWikipedia>
    </sitiosInteres>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornell-Pablo-eventos-rest/xmlEventosRepositorio/004fb1c0-c980-4517-bc11-88485449062e.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="004fb1c0-c980-4517-bc11-88485449062e" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>20 a tocar!.</nombre>
    <tipo>DanzaBaile</tipo>
    <fechaInicio>2021-06-12</fechaInicio>
    <fechaFin>2021-06-12</fechaFin>
    <resumen>Actuación musical de la Escuela Municipal de Música Maestro Barbieri.</resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=4388dfc243cc9710VgnVCM1000001d4a900aRCRD</url>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornellPablo-eventos-1/xmlEventosRepositorio/24b55775-539f-4753-9c9f-9fc1ffb3ded5.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="24b55775-539f-4753-9c9f-9fc1ffb3ded5" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>13 Lunas</nombre>
    <fechaInicio>2021-05-26 19:30:00.0</fechaInicio>
    <fechaFin>2021-05-26 23:59:00.0</fechaFin>
    <resumen>Menhir (Coco Moya e Iván Cebrián).  Kebyart Ensemble, Cuarteto de Saxofones.  Obras de Igor Stravinsky, Joan Magrané, José Río-Pareja (1973) - Parhelia (2018), 10’ , Franz Schubert, Raquel García-Tomás.</resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=47efc8f96f587710VgnVCM1000001d4a900aRCRD</url>
    <localizacion>CentroCentro</localizacion>
    <coordenadaLongitud>-3.692206111679657</coordenadaLongitud>
    <coordenadaLatitud>40.419011767401095</coordenadaLatitud>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornellPablo-eventos-1/xmlEventosCulturales/pruebaEvento.xml
<?xml version="1.0" encoding="UTF-8"?>
<eventoCultural id="11203871"
	xmlns="http://www.um.es/EventoCultural"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.um.es/EventoCultural EventoCultural.xsd ">
	<nombre>A nosotros nos daba igual</nombre>
	<fechaInicio>2021-06-23 00:00:00.0</fechaInicio>
	<fechaFin>2021-07-04 23:59:00.0</fechaFin>
	<resumen></resumen>
	<url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=becc8d9025e53710VgnVCM1000001d4a900aRCRD</url>
	<localizacion>Naves Espa√±ol en Matadero</localizacion>
	<coordenadaLongitud>
		-3.697247685884226
	</coordenadaLongitud>
	<coordenadaLatitud>
		40.39241374953321
	</coordenadaLatitud>
	<actuaciones>
		<frecuencia>WEEKLY</frecuencia>
		<dias>TU,WE,TH,FR,SA,SU</dias>
		<intervalo>1</intervalo>
	</actuaciones>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornell-Pablo-eventos-rest/xmlEventosRepositorio/53384425-1cf5-4f33-88a5-7e77ce4cf76e.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="53384425-1cf5-4f33-88a5-7e77ce4cf76e" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>A la luz de los focos</nombre>
    <tipo>CursosTalleres</tipo>
    <fechaInicio>2021-06-25</fechaInicio>
    <fechaFin>2021-06-25</fechaFin>
    <resumen>Pequeñas dosis de humor de la mano de grandes artistas.   A cargo del alumnado del 'Taller de Teatro del Centro Cultural Sara Montiel'. Profesora: Sara Monge.</resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=a6b9b6c834e99710VgnVCM2000001f4a900aRCRD</url>
    <localizacion>Centro Cultural Sara Montiel (Latina)</localizacion>
    <coordenadaLongitud>-3.775144917950534</coordenadaLongitud>
    <coordenadaLatitud>40.399764677637116</coordenadaLatitud>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
    <sitiosInteres>
        <titulo>Estación de Ciudad de la Imagen</titulo>
        <resumen>Ciudad de la Imagen es una estación de la línea ML-3 de Metro Ligero Oeste situada en el barrio homónimo de Pozuelo de Alarcón, junto a la calle Juan de Orduña. Abrió al público el 27 de julio de 2007. Su tarifa corresponde a la zona B1 según el Consorcio Regional de Transportes.  (...)</resumen>
        <urlWikipedia>https://es.wikipedia.org/wiki/Estaci%C3%B3n_de_Ciudad_de_la_Imagen</urlWikipedia>
    </sitiosInteres>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornell-Pablo-eventos-rest/xmlEventosRepositorio/81a290bb-ba32-46b9-80f2-d4bb76e0af55.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="81a290bb-ba32-46b9-80f2-d4bb76e0af55" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>El carro de Federico</nombre>
    <tipo>Fiestas</tipo>
    <fechaInicio>2021-06-27</fechaInicio>
    <fechaFin>2021-06-27</fechaFin>
    <resumen>Cuentacuentos.   Lugar: Plaza Antonio Cumella.   Sinopsis: Federico va de pueblo en pueblo con su carro lleno de cuentos, ero un día llegó a un pueblo donde nadie sabía leer, nadie excepto Don Señorón, ¿Qué pasará con la gente de aquel pueblo? ¿Qué pasará con todos esos cuentos del carro de Federico que esperan ser leídos o contados?  Edad recomendada:  a partir de 5 años.</resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=5b9de2f4dc2b9710VgnVCM2000001f4a900aRCRD</url>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornell-Pablo-eventos-rest/xmlEventosRepositorio/07aa21ae-2fe2-4ee1-8b82-888ac8716450.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="07aa21ae-2fe2-4ee1-8b82-888ac8716450" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>3</nombre>
    <tipo>TeatroPerformance</tipo>
    <fechaInicio>2021-06-11</fechaInicio>
    <fechaFin>2021-06-11</fechaFin>
    <resumen></resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=af755282f58a9710VgnVCM1000001d4a900aRCRD</url>
    <localizacion>Centro Sociocultural Alberto Sánchez (Puente de Vallecas)</localizacion>
    <coordenadaLongitud>-3.6556073868098493</coordenadaLongitud>
    <coordenadaLatitud>40.393612303425975</coordenadaLatitud>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
    <sitiosInteres>
        <titulo>Portazgo (Madrid)</titulo>
        <resumen>Portazgo es un barrio administrativo de Madrid que se encuentra al norte del distrito de Puente de Vallecas y está delimitado por las siguientes vías: * Avda. Pablo Neruda * C/Pío Felipe * Avda. Buenos Aires * Avda Mediterráneo  (...)</resumen>
        <urlWikipedia>https://es.wikipedia.org/wiki/Portazgo_%28Madrid%29</urlWikipedia>
    </sitiosInteres>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornellPablo-eventos-1/xmlEventosRepositorio/c8fef96d-3897-4867-8446-09c2a576db94.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="c8fef96d-3897-4867-8446-09c2a576db94" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>13 Lunas</nombre>
    <tipo>ProgramacionDestacadaAgendaCultura</tipo>
    <fechaInicio>2021-05-26</fechaInicio>
    <fechaFin>2021-05-26</fechaFin>
    <resumen>Menhir (Coco Moya e Iván Cebrián).  Kebyart Ensemble, Cuarteto de Saxofones.  Obras de Igor Stravinsky, Joan Magrané, José Río-Pareja (1973) - Parhelia (2018), 10’ , Franz Schubert, Raquel García-Tomás.</resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=47efc8f96f587710VgnVCM1000001d4a900aRCRD</url>
    <localizacion>CentroCentro</localizacion>
    <coordenadaLongitud>-3.692206111679657</coordenadaLongitud>
    <coordenadaLatitud>40.419011767401095</coordenadaLatitud>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
    <sitiosInteres>
        <titulo>Campeonato Mundial de Clubes de la FIFA 2001</titulo>
        <resumen>El Campeonato Mundial de Clubes 2001 fue un intento de la segunda edición del torneo organizado por la FIFA que fue cancelado. Estaba planeado que se llevase a cabo en España.  (...)</resumen>
        <urlWikipedia>https://es.wikipedia.org/wiki/Campeonato_Mundial_de_Clubes_de_la_FIFA_2001</urlWikipedia>
    </sitiosInteres>
</eventoCultural>
