=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornellPablo-eventos-1/xml/EventoCultural.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/EventoCultural"
	xmlns:tns="http://www.example.org/EventoCultural"
	elementFormDefault="qualified">

	<element name="eventoCultural">
		<complexType>
			<sequence>
				<element name="nombre" minOccurs="1" />
				<element name="fechaInicio" minOccurs="1" />
				<element name="fechaFin" minOccurs="1" />
				<element name="resumen" />
				<element name="url" minOccurs="1" />
				<element name="urlWikipedia" minOccurs="0" />
				<element name="localizacion" minOccurs="1" />
				<element name="coordenadaLongitud" type="tns:tipoCoordenada"
					minOccurs="1" />
				<element name="coordenadaLatitud" type="tns:tipoCoordenada"
					minOccurs="1" />
				<element name="actuaciones" type="tns:tipoActuaciones"
					minOccurs="0" />
			</sequence>
			<attribute name="id" use="required" />
		</complexType>
	</element>

	<complexType name="tipoActuaciones">
		<sequence>
			<element name="frecuencia" type="string" />
			<element name="dias" type="string" />
			<element name="intervalo" type="integer" />
		</sequence>
	</complexType>

	<simpleType name="tipoCoordenada">
		<restriction base="double" />
	</simpleType>

</schema>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornellPablo-eventos-1/xmlEventosCulturales/pruebaEvento2.xml
<?xml version="1.0" encoding="UTF-8"?>
<eventoCultural id="11322033"
	xmlns="http://www.um.es/EventoCultural"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.um.es/EventoCultural EventoCultural.xsd ">
	<nombre>13 Lunas</nombre>
	<fechaInicio>2021-05-26 19:30:00.0</fechaInicio>
	<fechaFin>2021-05-26 23:59:00.0</fechaFin>
	<resumen>Menhir (Coco Moya e Iván Cebrián). Kebyart Ensemble, Cuarteto
		de Saxofones. Obras de Igor Stravinsky, Joan Magrané, José Río-Pareja
		(1973) - Parhelia (2018), 10’ , Franz Schubert, Raquel García-Tomás.
	</resumen>
	<url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=47efc8f96f587710VgnVCM1000001d4a900aRCRD</url>
	<localizacion>CentroCentro</localizacion>
	<coordenadaLongitud>-3.692206111679657</coordenadaLongitud>
	<coordenadaLatitud>40.419011767401095</coordenadaLatitud>

</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornell-Pablo-eventos-rest/xmlEventosRepositorio/5d2c15e1-01a2-4082-8bbc-a788ca2a0d53.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="5d2c15e1-01a2-4082-8bbc-a788ca2a0d53" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>El campesino y la vaca</nombre>
    <tipo>CuentacuentosTiteresMarionetas</tipo>
    <fechaInicio>2021-06-20</fechaInicio>
    <fechaFin>2021-06-20</fechaFin>
    <resumen>Compañía entre manos.  Títeres.  Una historia que nos cuenta que los más importante no es lo que piensen los demás de nosotros.</resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=6615091bf32b9710VgnVCM1000001d4a900aRCRD</url>
    <localizacion>Centro Cultural Hortaleza</localizacion>
    <coordenadaLongitud>-3.6420353342333227</coordenadaLongitud>
    <coordenadaLatitud>40.476859845869534</coordenadaLatitud>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
    <sitiosInteres>
        <titulo>Estación de Hortaleza</titulo>
        <resumen>Hortaleza es una estación de la línea 4 del Metro de Madrid situada bajo la calle Virgen del Carmen, en el barrio de Pinar del Rey (distrito Hortaleza).  (...)</resumen>
        <urlWikipedia>https://es.wikipedia.org/wiki/Estaci%C3%B3n_de_Hortaleza</urlWikipedia>
    </sitiosInteres>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornell-Pablo-eventos-rest/xmlEventosRepositorio/9f5c6418-3829-49f6-94cc-c60d5bef58bc.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="9f5c6418-3829-49f6-94cc-c60d5bef58bc" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>50 años de la mujer en la Policía Municipal</nombre>
    <tipo></tipo>
    <fechaInicio>2021-06-03</fechaInicio>
    <fechaFin>2021-06-03</fechaFin>
    <resumen></resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=e323e980fbca9710VgnVCM2000001f4a900aRCRD</url>
    <localizacion>Sala de Exposiciones Maruja Mallo (Retiro)</localizacion>
    <coordenadaLongitud>-3.6772826298329093</coordenadaLongitud>
    <coordenadaLatitud>40.402190438836826</coordenadaLatitud>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
    <sitiosInteres>
        <titulo>Nave de motores de Pacífico</titulo>
        <resumen>La antigua central eléctrica de Pacífico (también denominada central térmica de Pacífico o fábrica de electricidad de Pacífico) es una instalación industrial perteneciente al Metro de Madrid. El 11 de abril de 2013, la Dirección General de Patrimonio Histórico de la Comunidad de Madrid la declaró (...)</resumen>
        <urlWikipedia>https://es.wikipedia.org/wiki/Nave_de_motores_de_Pac%C3%ADfico</urlWikipedia>
    </sitiosInteres>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornell-Pablo-eventos-rest/xmlEventosRepositorio/b909944b-d6ea-4e75-812c-0e8c3fc64e6b.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="b909944b-d6ea-4e75-812c-0e8c3fc64e6b" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>A nosotros nos daba igual</nombre>
    <tipo>ProgramacionDestacadaAgendaCultura</tipo>
    <fechaInicio>2021-06-24</fechaInicio>
    <fechaFin>2021-06-24</fechaFin>
    <resumen></resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=becc8d9025e53710VgnVCM1000001d4a900aRCRD</url>
    <localizacion>Naves Español en Matadero</localizacion>
    <coordenadaLongitud>-3.697247685884226</coordenadaLongitud>
    <coordenadaLatitud>40.39241374953321</coordenadaLatitud>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
    <sitiosInteres>
        <titulo>Mercado de Guillermo de Osma</titulo>
        <resumen>El Mercado Guillermo de Osma es uno de los dos mercados municipales de abastos del distrito de Arganzuela (Madrid).José Pamias Ruiz (Firm), (1976), Guía urbana de Madrid, Volumen 1, Primera edición, Madrid, Página 82 La denominación del mercado es en honor del diplomático español del siglo XIX (...)</resumen>
        <urlWikipedia>https://es.wikipedia.org/wiki/Mercado_de_Guillermo_de_Osma</urlWikipedia>
    </sitiosInteres>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornell-Pablo-eventos-rest/xmlEventosRepositorio/0b70341d-c679-4c81-a1da-035bd9a66e2c.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="0b70341d-c679-4c81-a1da-035bd9a66e2c" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>100 años de la línea norte-sur</nombre>
    <tipo></tipo>
    <fechaInicio>2021-06-10</fechaInicio>
    <fechaFin>2021-06-10</fechaFin>
    <resumen></resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=76b8df069e5e9710VgnVCM2000001f4a900aRCRD</url>
    <localizacion>Junta Municipal del Distrito de Retiro</localizacion>
    <coordenadaLongitud>-3.6772826298329093</coordenadaLongitud>
    <coordenadaLatitud>40.402190438836826</coordenadaLatitud>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
    <sitiosInteres>
        <titulo>Nave de motores de Pacífico</titulo>
        <resumen>La antigua central eléctrica de Pacífico (también denominada central térmica de Pacífico o fábrica de electricidad de Pacífico) es una instalación industrial perteneciente al Metro de Madrid. El 11 de abril de 2013, la Dirección General de Patrimonio Histórico de la Comunidad de Madrid la declaró (...)</resumen>
        <urlWikipedia>https://es.wikipedia.org/wiki/Nave_de_motores_de_Pac%C3%ADfico</urlWikipedia>
    </sitiosInteres>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornell-Pablo-eventos-rest/xmlEventosRepositorio/8c1f428f-9eae-4d01-b67e-971803c4c1af.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="8c1f428f-9eae-4d01-b67e-971803c4c1af" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>A la luz del candil</nombre>
    <tipo>DanzaBaile</tipo>
    <fechaInicio>2021-06-12</fechaInicio>
    <fechaFin>2021-06-12</fechaFin>
    <resumen>DANZA.   COMPAÑÍA ESTELA ALONSO,   Espectáculo que pone en valor la famosa “Escuela Bolera”. Danza basada en aquellas bailarinas acostumbradas a los bailes en la corte, de técnica depurada que empezaron a empaparse, gracias a los cafés cantantes, del arranque y brío, así como del expresionismo y raza del mundo del flamenco.  La Escuela Bolera es una danza española con una ejecución técnica rápida y vivaz enriquecida con movimientos corporales más raciales, envueltos con el sonido de las castañuelas y al compás de esos ritmos flamencos que dan lugar a bellísimos bailes repletos de gracia y destreza.    Dirección y coreografía:  Estela Alonso.    Será obligatorio el uso de mascarilla y gel hidroalcohólico en la entrada así como atender en todo momento a las indicaciones del personal para cumplir las medidas preventivas dictadas por las autoridades sanitarias.    AFORO LIMITADO.    ENTRADA GRATUITA PREVIA RESERVA EN:    https://www.eventbrite.es/e/entradas-danza-a-la-luz-del-candil-156537414621         Reserva del 10% de las entradas a mayores de 65 años. Estas entradas se podrán adquirir de forma presencial en el centro cultural correspondiente.</resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=88e07faaa6e99710VgnVCM2000001f4a900aRCRD</url>
    <localizacion>Centro Cultural Moncloa (Moncloa - Aravaca)</localizacion>
    <coordenadaLongitud>-3.7188765163188293</coordenadaLongitud>
    <coordenadaLatitud>40.435209393826675</coordenadaLatitud>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
    <sitiosInteres>
        <titulo>Arco de la Victoria</titulo>
        <resumen>El Arco de la Victoria de Madrid (popularmente denominado como Puerta de la Moncloa por tener cierta similitud con las puertas de Alcalá y Toledo y también como Arco del Triunfo), es un arco de triunfo construido entre el periodo que va desde el año 1950 a 1956 (...)</resumen>
        <urlWikipedia>https://es.wikipedia.org/wiki/Arco_de_la_Victoria</urlWikipedia>
    </sitiosInteres>
</eventoCultural>

=== PabloCegarra/proyecto-CegarraTornellPablo/CegarraTornell-Pablo-eventos-rest/xmlEventosRepositorio/ca1d90e9-a0fb-4206-b04d-ae6e9687129a.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<eventoCultural xmlns="http://www.um.es/EventoCultural" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="ca1d90e9-a0fb-4206-b04d-ae6e9687129a" xsi:schemaLocation="EventoCultural.xsd">
    <nombre>El Dragón Chef</nombre>
    <tipo>CuentacuentosTiteresMarionetas</tipo>
    <fechaInicio>2021-06-12</fechaInicio>
    <fechaFin>2021-06-12</fechaFin>
    <resumen>Al dragón le gustaba mucho cocinar, tenía un puesto de maíz y piensa en echar pimienta. Cuando se forma una nube de polvo, el dragón estornuda y empieza a explotar el maíz y a convertirse en palomitas. Así es como aprendió a hacerlas, por lo que aprovecha este descubrimiento para venderlas.</resumen>
    <url>http://www.madrid.es/sites/v/index.jsp?vgnextchannel=ca9671ee4a9eb410VgnVCM100000171f5a0aRCRD&amp;vgnextoid=ae55cd29827cf610VgnVCM2000001f4a900aRCRD</url>
    <localizacion>Centro Cultural La Vaguada (Fuencarral - El Pardo)</localizacion>
    <coordenadaLongitud>-3.709138377702435</coordenadaLongitud>
    <coordenadaLatitud>40.47900813206291</coordenadaLatitud>
    <actuaciones>
        <frecuencia>WEEKLY</frecuencia>
        <dias></dias>
        <intervalo>1</intervalo>
    </actuaciones>
    <sitiosInteres>
        <titulo>Estación de Herrera Oria</titulo>
        <resumen>Herrera Oria es una estación de la línea 9 del Metro de Madrid en España situada bajo la calle Ginzo de Limia, en el tramo comprendido entre la Avenida del Cardenal Herrera Oria y la Avenida de la Ilustración, entre los barrios de El Pilar y La Paz, ambos pertenecientes al distrito Fuencarral-El (...)</resumen>
        <urlWikipedia>https://es.wikipedia.org/wiki/Estaci%C3%B3n_de_Herrera_Oria</urlWikipedia>
    </sitiosInteres>
</eventoCultural>
